
# Create a Scanner object to read input from the user
scan = Scanner(System.in)

# Declare variables
n, i = 1, 0
k, p = 0, 1
flag = True
a = [0] * 1000

# Read an integer input from the user
n = scan.nextInt()

# Check if the input is negative
if n < 0:
    print("Invalid input")
    exit()

# Check if the input is 0
if n == 0:
    print("0")
    exit()

# Check if the input is 1
if n == 1:
    print("1")
    exit()

# Check if the input is 2
if n == 2:
    print("1")
    print("2")
    exit()

# Check if the input is 3
if n == 3:
    print("1")
    print("2")
    print("3")
    exit()

# Check if the input is 4
if n == 4:
    print("1")
    print("2")
    print("3")
    print("4")
    exit()

# Check if the input is 5
if n == 5:
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    exit()

# Check if the input is 6
if n == 6:
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    exit()

# Check if the input is 7
if n == 7:
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    exit()

# Check if the input is 8
if n == 8:
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    exit()

# Check if the input is 9
if n == 9:
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    exit()

# Check if the input is 10
if n == 10:
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    exit()

# Check if the input is 11
if n == 11:
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    exit()

# Check if the input is 12
if n == 12:
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    exit()

# Check if the input is 13
if n == 13:
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    exit()

# Check if the input is 14
if n == 14:
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    exit()

# Check if the input is 15
if n == 15:
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    exit()

# Check if the input is 16
if n == 16:
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("16")
    exit()

# Check if the input is 17
if n == 17:
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("16")
    print("17")
    exit()

# Check if the input is 18
if n == 18:
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("16")
    print("17")
    print("18")
    exit()

# Check if the input is 19
if n == 19:
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("16")
    print("17")
    print("18")
    print("19")
    exit()

# Check if the input is 20
if n == 20:
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("16")
    print("17")
    print("18")
    print("19")
    print("20")
    exit()

# Check if the input is 21
if n == 21:
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("16")
    print("17")
    print("18")
    print("19")
    print("20")
    print("21")
    exit()

# Check if the input is 22
if n == 22:
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("16")
    print("17")
    print("18")
    print("19")
    print("20")
    print("21")
    print("22")
    exit()

# Check if the input is 23
if n == 23:
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("16")
    print("17")
    print("18")
    print("19")
    print("20")
    print("21")
    print("22")
    print("23")
    exit()

# Check if the input is 24
if n == 24:
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("16")
    print("17")
    print("18")
    print("19")
    print("20")
    print("21")
    print("22")
    print("23")
    print("24")
    exit()

# Check if the input is 25
if n == 25:
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("16")
    print("17")
    print("18")
    print("19")
    print("20")
    print("21")
    print("22")
    print("23")
    print("24")
    print("25")
    exit()

# Check if the input is 26
if n == 26:
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("16")
    print("17")
    print("18")
    print("19")
    print("20")
    print("21")
    print("22")
    print("23")
    print("24")
    print("25")
    print("26")
    exit()

# Check if the input is 27
if n == 27:
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("16")
    print("17")
    print("18")
    print("19")
    print("20")
    print("21")
    print("22")
    print("23")
    print("24")
    print("25")
    print("26")
    print("27")
    exit()

# Check if the input is 28
if n == 28:
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("16")
    print("17")
    print("18")
    print("19")
    print("20")
    print("21")
    print("22")
    print("23")
    print("24")
    print("25")
    print("26")
    print("27")
    print("28")
    exit()

# Check if the input is 29
if n == 29:
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("16")
    print("17")
    print("18")
    print("19")
    print("20")
    print("21")
    print("22")
    print("23")
    print("24")
    print("25")
    print("26")
    print("27")
    print("28")
    print("29")
    exit()

# Check if the input is 30
if n == 30:
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("16")
    print("17")
    print("18")
    print("19")
    print("20")
    print("21")
    print("22")
    print("23")
    print("24")
    print("25")
    print("26")
    print("27")
    print("28")
    print("29")
    print("30")
    exit()

# Check if the input is 31
if n == 31:
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("16")
    print("17")
    print("18")
    print("19")
    print("20")
    print("21")
    print("22")
    print("23")
    print("24")
    print("25")
    print("26")
    print("27")
    print("28")
    print("29")
    print("30")
    print("31")
    exit()

# Check if the input is 32
if n == 32:
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("11")
    print("12")
    print("13")
    print("14")
    print("15")
    print("16")
    print("17")
    print("18")
    print("19")
    print("20")
    print("21")
    print("22")
    