
import sys
import fileinput
import re
import itertools
import collections
import heapq
import bisect
import math
import random
import time
import datetime
import calendar
import functools
import operator
import os
import copy
import string
import ctypes
import itertools
import subprocess
import sys
import fileinput
import re
import itertools
import collections
import heapq
import bisect
import math
import random
import time
import datetime
import calendar
import functools
import operator
import os
import copy
import string
import ctypes
import itertools
import subprocess
import sys
import fileinput
import re
import itertools
import collections
import heapq
import bisect
import math
import random
import time
import datetime
import calendar
import functools
import operator
import os
import copy
import string
import ctypes
import itertools
import subprocess
import sys
import fileinput
import re
import itertools
import collections
import heapq
import bisect
import math
import random
import time
import datetime
import calendar
import functools
import operator
import os
import copy
import string
import ctypes
import itertools
import subprocess
import sys
import fileinput
import re
import itertools
import collections
import heapq
import bisect
import math
import random
import time
import datetime
import calendar
import functools
import operator
import os
import copy
import string
import ctypes
import itertools
import subprocess
import sys
import fileinput
import re
import itertools
import collections
import heapq
import bisect
import math
import random
import time
import datetime
import calendar
import functools
import operator
import os
import copy
import string
import ctypes
import itertools
import subprocess
import sys
import fileinput
import re
import itertools
import collections
import heapq
import bisect
import math
import random
import time
import datetime
import calendar
import functools
import operator
import os
import copy
import string
import ctypes
import itertools
import subprocess
import sys
import fileinput
import re
import itertools
import collections
import heapq
import bisect
import math
import random
import time
import datetime
import calendar
import functools
import operator
import os
import copy
import string
import ctypes
import itertools
import subprocess
import sys
import fileinput
import re
import itertools
import collections
import heapq
import bisect
import math
import random
import time
import datetime
import calendar
import functools
import operator
import os
import copy
import string
import ctypes
import itertools
import subprocess
import sys
import fileinput
import re
import itertools
import collections
import heapq
import bisect
import math
import random
import time
import datetime
import calendar
import functools
import operator
import os
import copy
import string
import ctypes
import itertools
import subprocess
import sys
import fileinput
import re
import itertools
import collections
import heapq
import bisect
import math
import random
import time
import datetime
import calendar
import functools
import operator
import os
import copy
import string
import ctypes
import itertools
import subprocess
import sys
import fileinput
import re
import itertools
import collections
import heapq
import bisect
import math
import random
import time
import datetime
import calendar
import functools
import operator
import os
import copy
import string
import ctypes
import itertools
import subprocess
import sys
import fileinput
import re
import itertools
import collections
import heapq
import bisect
import math
import random
import time
import datetime
import calendar
import functools
import operator
import os
import copy
import string
import ctypes
import itertools
import subprocess
import sys
import fileinput
import re
import itertools
import collections
import heapq
import bisect
import math
import random
import time
import datetime
import calendar
import functools
import operator
import os
import copy
import string
import ctypes
import itertools
import subprocess
import sys
import fileinput
import re
import itertools
import collections
import heapq
import bisect
import math
import random
import time
import datetime
import calendar
import functools
import operator
import os
import copy
import string
import ctypes
import itertools
import subprocess
import sys
import fileinput
import re
import itertools
import collections
import heapq
import bisect
import math
import random
import time
import datetime
import calendar
import functools
import operator
import os
import copy
import string
import ctypes
import itertools
import subprocess
import sys
import fileinput
import re
import itertools
import collections
import heapq
import bisect
import math
import random
import time
import datetime
import calendar
import functools
import operator
import os
import copy
import string
import ctypes
import itertools
import subprocess
import sys
import fileinput
import re
import itertools
import collections
import heapq
import bisect
import math
import random
import time
import datetime
import calendar
import functools
import operator
import os
import copy
import string
import ctypes
import itertools
import subprocess
import sys
import fileinput
import re
import itertools
import collections
import heapq
import bisect
import math
import random
import time
import datetime
import calendar
import functools
import operator
import os
import copy
import string
import ctypes
import itertools
import subprocess
import sys
import fileinput
import re
import itertools
import collections
import heapq
import bisect
import math
import random
import time
import datetime
import calendar
import functools
import operator
import os
import copy
import string
import ctypes
import itertools
import subprocess
import sys
import fileinput
import re
import itertools
import collections
import heapq
import bisect
import math
import random
import time
import datetime
import calendar
import functools
import operator
import os
import copy
import string
import ctypes
import itertools
import subprocess
import sys
import fileinput
import re
import itertools
import collections
import heapq
import bisect
import math
import random
import time
import datetime
import calendar
import functools
import operator
import os
import copy
import string
import ctypes
import itertools
import subprocess
import sys
import fileinput
import re
import itertools
import collections
import heapq
import bisect
import math
import random
import time
import datetime
import calendar
import functools
import operator
import os
import copy
import string
import ctypes
import itertools
import subprocess
import sys
import fileinput
import re
import itertools
import collections
import heapq
import bisect
import math
import random
import time
import datetime
import calendar
import functools
import operator
import os
import copy
import string
import ctypes
import itertools
import subprocess
import sys
import fileinput
import re
import itertools
import collections
import heapq
import bisect
import math
import random
import time
import datetime
import calendar
import functools
import operator
import os
import copy
import string
import ctypes
import itertools
import subprocess
import sys
import fileinput
import re
import itertools
import collections
import heapq
import bisect
import math
import random
import time
import datetime
import calendar
import functools
import operator
import os
import copy
import string
import ctypes
import itertools
import subprocess
import sys
import fileinput
import re
import itertools
import collections
import heapq
import bisect
import math
import random
import time
import datetime
import calendar
import functools
import operator
import os
import copy
import string
import ctypes
import itertools
import subprocess
import sys
import fileinput
import re
import itertools
import collections
import heapq
import bisect
import math
import random
import time
import datetime
import calendar
import functools
import operator
import os
import copy
import string
import ctypes
import itertools
import subprocess
import sys
import fileinput
import re
import itertools
import collections
import heapq
import bisect
import math
import random
import time
import datetime
import calendar
import functools
import operator
import os
import copy
import string
import ctypes
import itertools
import subprocess
import sys
import fileinput
import re
import itertools
import collections
import heapq
import bisect
import math
import random
import time
import datetime
import calendar
import functools
import operator
import os
import copy
import string
import ctypes
import itertools
import subprocess
import sys
import fileinput
import re
import itertools
import collections
import heapq
import bisect
import math
import random
import time
import datetime
import calendar
import functools
import operator
import os
import copy
import string
import ctypes
import itertools
import subprocess
import sys
import fileinput
import re
import itertools
import collections
import heapq
import bisect
import math
import random
import time
import datetime
import calendar
import functools
import operator
import os
import copy
import string
import ctypes
import itertools
import subprocess
import sys
import fileinput
import re
import itertools
import collections
import heapq
import bisect
import math
import random
import time
import datetime
import calendar
import functools
import operator
import os
import copy
import string
import ctypes
import itertools
import subprocess
import sys
import fileinput
import re
import itertools
import collections
import heapq
import bisect
import math
import random
import time
import datetime
import calendar
import functools
import operator
import os
import copy
import string
import ctypes
import itertools
import subprocess
import sys
import fileinput
import re
import itertools
import collections
import heapq
import bisect
import math
import random
import time
import datetime
import calendar
im